zotero:
  user_id: ???
  api_key: ???
  include_path: null

source:
  arxiv:
    query: ???

email:
  sender: ???
  receiver: ???
  smtp_server: ???
  smtp_port: ???
  sender_password: ???

llm:
  api:
    key: ???
    base_url: ???
  timeout: 180
  generation_kwargs:
    max_tokens: 16384
    temperature: 0.4
    model: ???
  language: English

reranker:
  local:
    model: Qwen/Qwen3-Embedding-0.6B
  api:
    key: ???
    base_url: ???
    model: ???

executor:
  debug: false
  send_empty: false
  max_workers: 10
  max_paper_num: 100
  source: ???
  reranker: local